platform :ios, '9.0'

use_frameworks!

target 'PagedCollectionView_Example' do
  pod 'PagedCollectionView', :path => '../'

  target 'PagedCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
