platform :ios, '9.0'

use_frameworks!

target 'PagedCollectionView_Example' do
  pod 'PagedCollectionView', :path => '../'

  target 'PagedCollectionView_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end 
end
